// GENERATED by tools/gen_sysreg_table.py - do not edit by hand.
#include "ohv_internal.h"
namespace ohv {
static const SysRegDesc kTable[] = {
    {0x8004,5,0,0,false},
    {0x8005,5,0,0,false},
    {0x8006,5,0,0,false},
    {0x8007,5,0,0,false},
    {0x800c,5,0,0,false},
    {0x800d,5,0,0,false},
    {0x800e,5,0,0,false},
    {0x800f,5,0,0,false},
    {0x8010,3,64,OHV_STATE_DEBUG,true},
    {0x8012,0,0,0,false},
    {0x8014,5,0,0,false},
    {0x8015,5,0,0,false},
    {0x8016,5,0,0,false},
    {0x8017,5,0,0,false},
    {0x801c,5,0,0,false},
    {0x801d,5,0,0,false},
    {0x801e,5,0,0,false},
    {0x801f,5,0,0,false},
    {0x8024,5,0,0,false},
    {0x8025,5,0,0,false},
    {0x8026,5,0,0,false},
    {0x8027,5,0,0,false},
    {0x802c,5,0,0,false},
    {0x802d,5,0,0,false},
    {0x802e,5,0,0,false},
    {0x802f,5,0,0,false},
    {0x8034,5,0,0,false},
    {0x8035,5,0,0,false},
    {0x8036,5,0,0,false},
    {0x8037,5,0,0,false},
    {0x803c,5,0,0,false},
    {0x803d,5,0,0,false},
    {0x803e,5,0,0,false},
    {0x803f,5,0,0,false},
    {0x8044,5,0,0,false},
    {0x8045,5,0,0,false},
    {0x8046,5,0,0,false},
    {0x8047,5,0,0,false},
    {0x804c,5,0,0,false},
    {0x804d,5,0,0,false},
    {0x804e,5,0,0,false},
    {0x804f,5,0,0,false},
    {0x8054,5,0,0,false},
    {0x8055,5,0,0,false},
    {0x8056,5,0,0,false},
    {0x8057,5,0,0,false},
    {0x805c,5,0,0,false},
    {0x805d,5,0,0,false},
    {0x805e,5,0,0,false},
    {0x805f,5,0,0,false},
    {0x8064,5,0,0,false},
    {0x8065,5,0,0,false},
    {0x8066,5,0,0,false},
    {0x8067,5,0,0,false},
    {0x806c,5,0,0,false},
    {0x806d,5,0,0,false},
    {0x806e,5,0,0,false},
    {0x806f,5,0,0,false},
    {0x8074,5,0,0,false},
    {0x8075,5,0,0,false},
    {0x8076,5,0,0,false},
    {0x8077,5,0,0,false},
    {0x807c,5,0,0,false},
    {0x807d,5,0,0,false},
    {0x807e,5,0,0,false},
    {0x807f,5,0,0,false},
    {0xc000,5,0,0,false},
    {0xc005,5,0,0,false},
    {0xc020,5,0,0,false},
    {0xc021,5,0,0,false},
    {0xc028,5,0,0,false},
    {0xc029,5,0,0,false},
    {0xc030,5,0,0,false},
    {0xc031,5,0,0,false},
    {0xc038,5,0,0,false},
    {0xc039,5,0,0,false},
    {0xc03a,5,0,0,false},
    {0xc080,1,12,OHV_STATE_SYSREGS,true},
    {0xc082,1,13,OHV_STATE_SYSREGS,true},
    {0xc100,1,0,OHV_STATE_SYSREGS,true},
    {0xc101,1,1,OHV_STATE_SYSREGS,true},
    {0xc102,1,2,OHV_STATE_SYSREGS,true},
    {0xc108,2,33,OHV_STATE_PTRAUTH_ARM,true},
    {0xc109,2,32,OHV_STATE_PTRAUTH_ARM,true},
    {0xc10a,2,35,OHV_STATE_PTRAUTH_ARM,true},
    {0xc10b,2,34,OHV_STATE_PTRAUTH_ARM,true},
    {0xc110,2,37,OHV_STATE_PTRAUTH_ARM,true},
    {0xc111,2,36,OHV_STATE_PTRAUTH_ARM,true},
    {0xc112,2,39,OHV_STATE_PTRAUTH_ARM,true},
    {0xc113,2,38,OHV_STATE_PTRAUTH_ARM,true},
    {0xc118,2,31,OHV_STATE_PTRAUTH_ARM,true},
    {0xc119,2,30,OHV_STATE_PTRAUTH_ARM,true},
    {0xc200,1,14,OHV_STATE_SYSREGS,true},
    {0xc201,1,3,OHV_STATE_SYSREGS,true},
    {0xc208,0,4,0,false},
    {0xc288,1,15,OHV_STATE_SYSREGS,true},
    {0xc289,1,16,OHV_STATE_SYSREGS,true},
    {0xc290,1,5,OHV_STATE_SYSREGS,true},
    {0xc300,1,4,OHV_STATE_SYSREGS,true},
    {0xc3a0,0,6,0,false},
    {0xc510,1,6,OHV_STATE_SYSREGS,true},
    {0xc518,1,7,OHV_STATE_SYSREGS,true},
    {0xc600,1,8,OHV_STATE_SYSREGS,true},
    {0xc681,1,17,OHV_STATE_SYSREGS,true},
    {0xc684,0,1,0,false},
    {0xc708,1,20,OHV_STATE_SYSREGS,true},
    {0xd000,0,7,0,false},
    {0xde82,0,2,0,false},
    {0xde83,0,3,0,false},
    {0xdf19,1,18,OHV_STATE_SYSREGS,true},
    {0xdf1a,1,9,OHV_STATE_SYSREGS,true},
    {0xe208,0,5,0,false},
};
const SysRegDesc *sysreg_lookup(uint16_t enc) {
    switch (enc) {
    case HV_SYS_REG_DBGBVR0_EL1: return &kTable[0];
    case HV_SYS_REG_DBGBCR0_EL1: return &kTable[1];
    case HV_SYS_REG_DBGWVR0_EL1: return &kTable[2];
    case HV_SYS_REG_DBGWCR0_EL1: return &kTable[3];
    case HV_SYS_REG_DBGBVR1_EL1: return &kTable[4];
    case HV_SYS_REG_DBGBCR1_EL1: return &kTable[5];
    case HV_SYS_REG_DBGWVR1_EL1: return &kTable[6];
    case HV_SYS_REG_DBGWCR1_EL1: return &kTable[7];
    case HV_SYS_REG_MDCCINT_EL1: return &kTable[8];
    case HV_SYS_REG_MDSCR_EL1: return &kTable[9];
    case HV_SYS_REG_DBGBVR2_EL1: return &kTable[10];
    case HV_SYS_REG_DBGBCR2_EL1: return &kTable[11];
    case HV_SYS_REG_DBGWVR2_EL1: return &kTable[12];
    case HV_SYS_REG_DBGWCR2_EL1: return &kTable[13];
    case HV_SYS_REG_DBGBVR3_EL1: return &kTable[14];
    case HV_SYS_REG_DBGBCR3_EL1: return &kTable[15];
    case HV_SYS_REG_DBGWVR3_EL1: return &kTable[16];
    case HV_SYS_REG_DBGWCR3_EL1: return &kTable[17];
    case HV_SYS_REG_DBGBVR4_EL1: return &kTable[18];
    case HV_SYS_REG_DBGBCR4_EL1: return &kTable[19];
    case HV_SYS_REG_DBGWVR4_EL1: return &kTable[20];
    case HV_SYS_REG_DBGWCR4_EL1: return &kTable[21];
    case HV_SYS_REG_DBGBVR5_EL1: return &kTable[22];
    case HV_SYS_REG_DBGBCR5_EL1: return &kTable[23];
    case HV_SYS_REG_DBGWVR5_EL1: return &kTable[24];
    case HV_SYS_REG_DBGWCR5_EL1: return &kTable[25];
    case HV_SYS_REG_DBGBVR6_EL1: return &kTable[26];
    case HV_SYS_REG_DBGBCR6_EL1: return &kTable[27];
    case HV_SYS_REG_DBGWVR6_EL1: return &kTable[28];
    case HV_SYS_REG_DBGWCR6_EL1: return &kTable[29];
    case HV_SYS_REG_DBGBVR7_EL1: return &kTable[30];
    case HV_SYS_REG_DBGBCR7_EL1: return &kTable[31];
    case HV_SYS_REG_DBGWVR7_EL1: return &kTable[32];
    case HV_SYS_REG_DBGWCR7_EL1: return &kTable[33];
    case HV_SYS_REG_DBGBVR8_EL1: return &kTable[34];
    case HV_SYS_REG_DBGBCR8_EL1: return &kTable[35];
    case HV_SYS_REG_DBGWVR8_EL1: return &kTable[36];
    case HV_SYS_REG_DBGWCR8_EL1: return &kTable[37];
    case HV_SYS_REG_DBGBVR9_EL1: return &kTable[38];
    case HV_SYS_REG_DBGBCR9_EL1: return &kTable[39];
    case HV_SYS_REG_DBGWVR9_EL1: return &kTable[40];
    case HV_SYS_REG_DBGWCR9_EL1: return &kTable[41];
    case HV_SYS_REG_DBGBVR10_EL1: return &kTable[42];
    case HV_SYS_REG_DBGBCR10_EL1: return &kTable[43];
    case HV_SYS_REG_DBGWVR10_EL1: return &kTable[44];
    case HV_SYS_REG_DBGWCR10_EL1: return &kTable[45];
    case HV_SYS_REG_DBGBVR11_EL1: return &kTable[46];
    case HV_SYS_REG_DBGBCR11_EL1: return &kTable[47];
    case HV_SYS_REG_DBGWVR11_EL1: return &kTable[48];
    case HV_SYS_REG_DBGWCR11_EL1: return &kTable[49];
    case HV_SYS_REG_DBGBVR12_EL1: return &kTable[50];
    case HV_SYS_REG_DBGBCR12_EL1: return &kTable[51];
    case HV_SYS_REG_DBGWVR12_EL1: return &kTable[52];
    case HV_SYS_REG_DBGWCR12_EL1: return &kTable[53];
    case HV_SYS_REG_DBGBVR13_EL1: return &kTable[54];
    case HV_SYS_REG_DBGBCR13_EL1: return &kTable[55];
    case HV_SYS_REG_DBGWVR13_EL1: return &kTable[56];
    case HV_SYS_REG_DBGWCR13_EL1: return &kTable[57];
    case HV_SYS_REG_DBGBVR14_EL1: return &kTable[58];
    case HV_SYS_REG_DBGBCR14_EL1: return &kTable[59];
    case HV_SYS_REG_DBGWVR14_EL1: return &kTable[60];
    case HV_SYS_REG_DBGWCR14_EL1: return &kTable[61];
    case HV_SYS_REG_DBGBVR15_EL1: return &kTable[62];
    case HV_SYS_REG_DBGBCR15_EL1: return &kTable[63];
    case HV_SYS_REG_DBGWVR15_EL1: return &kTable[64];
    case HV_SYS_REG_DBGWCR15_EL1: return &kTable[65];
    case HV_SYS_REG_MIDR_EL1: return &kTable[66];
    case HV_SYS_REG_MPIDR_EL1: return &kTable[67];
    case HV_SYS_REG_ID_AA64PFR0_EL1: return &kTable[68];
    case HV_SYS_REG_ID_AA64PFR1_EL1: return &kTable[69];
    case HV_SYS_REG_ID_AA64DFR0_EL1: return &kTable[70];
    case HV_SYS_REG_ID_AA64DFR1_EL1: return &kTable[71];
    case HV_SYS_REG_ID_AA64ISAR0_EL1: return &kTable[72];
    case HV_SYS_REG_ID_AA64ISAR1_EL1: return &kTable[73];
    case HV_SYS_REG_ID_AA64MMFR0_EL1: return &kTable[74];
    case HV_SYS_REG_ID_AA64MMFR1_EL1: return &kTable[75];
    case HV_SYS_REG_ID_AA64MMFR2_EL1: return &kTable[76];
    case HV_SYS_REG_SCTLR_EL1: return &kTable[77];
    case HV_SYS_REG_CPACR_EL1: return &kTable[78];
    case HV_SYS_REG_TTBR0_EL1: return &kTable[79];
    case HV_SYS_REG_TTBR1_EL1: return &kTable[80];
    case HV_SYS_REG_TCR_EL1: return &kTable[81];
    case HV_SYS_REG_APIAKEYLO_EL1: return &kTable[82];
    case HV_SYS_REG_APIAKEYHI_EL1: return &kTable[83];
    case HV_SYS_REG_APIBKEYLO_EL1: return &kTable[84];
    case HV_SYS_REG_APIBKEYHI_EL1: return &kTable[85];
    case HV_SYS_REG_APDAKEYLO_EL1: return &kTable[86];
    case HV_SYS_REG_APDAKEYHI_EL1: return &kTable[87];
    case HV_SYS_REG_APDBKEYLO_EL1: return &kTable[88];
    case HV_SYS_REG_APDBKEYHI_EL1: return &kTable[89];
    case HV_SYS_REG_APGAKEYLO_EL1: return &kTable[90];
    case HV_SYS_REG_APGAKEYHI_EL1: return &kTable[91];
    case HV_SYS_REG_SPSR_EL1: return &kTable[92];
    case HV_SYS_REG_ELR_EL1: return &kTable[93];
    case HV_SYS_REG_SP_EL0: return &kTable[94];
    case HV_SYS_REG_AFSR0_EL1: return &kTable[95];
    case HV_SYS_REG_AFSR1_EL1: return &kTable[96];
    case HV_SYS_REG_ESR_EL1: return &kTable[97];
    case HV_SYS_REG_FAR_EL1: return &kTable[98];
    case HV_SYS_REG_PAR_EL1: return &kTable[99];
    case HV_SYS_REG_MAIR_EL1: return &kTable[100];
    case HV_SYS_REG_AMAIR_EL1: return &kTable[101];
    case HV_SYS_REG_VBAR_EL1: return &kTable[102];
    case HV_SYS_REG_CONTEXTIDR_EL1: return &kTable[103];
    case HV_SYS_REG_TPIDR_EL1: return &kTable[104];
    case HV_SYS_REG_CNTKCTL_EL1: return &kTable[105];
    case HV_SYS_REG_CSSELR_EL1: return &kTable[106];
    case HV_SYS_REG_TPIDR_EL0: return &kTable[107];
    case HV_SYS_REG_TPIDRRO_EL0: return &kTable[108];
    case HV_SYS_REG_CNTV_CTL_EL0: return &kTable[109];
    case HV_SYS_REG_CNTV_CVAL_EL0: return &kTable[110];
    case HV_SYS_REG_SP_EL1: return &kTable[111];
    default: return nullptr;
    }
}
const char *sysreg_name(uint16_t enc) {
    switch (enc) {
        case HV_SYS_REG_DBGBVR0_EL1: return "HV_SYS_REG_DBGBVR0_EL1";
        case HV_SYS_REG_DBGBCR0_EL1: return "HV_SYS_REG_DBGBCR0_EL1";
        case HV_SYS_REG_DBGWVR0_EL1: return "HV_SYS_REG_DBGWVR0_EL1";
        case HV_SYS_REG_DBGWCR0_EL1: return "HV_SYS_REG_DBGWCR0_EL1";
        case HV_SYS_REG_DBGBVR1_EL1: return "HV_SYS_REG_DBGBVR1_EL1";
        case HV_SYS_REG_DBGBCR1_EL1: return "HV_SYS_REG_DBGBCR1_EL1";
        case HV_SYS_REG_DBGWVR1_EL1: return "HV_SYS_REG_DBGWVR1_EL1";
        case HV_SYS_REG_DBGWCR1_EL1: return "HV_SYS_REG_DBGWCR1_EL1";
        case HV_SYS_REG_MDCCINT_EL1: return "HV_SYS_REG_MDCCINT_EL1";
        case HV_SYS_REG_MDSCR_EL1: return "HV_SYS_REG_MDSCR_EL1";
        case HV_SYS_REG_DBGBVR2_EL1: return "HV_SYS_REG_DBGBVR2_EL1";
        case HV_SYS_REG_DBGBCR2_EL1: return "HV_SYS_REG_DBGBCR2_EL1";
        case HV_SYS_REG_DBGWVR2_EL1: return "HV_SYS_REG_DBGWVR2_EL1";
        case HV_SYS_REG_DBGWCR2_EL1: return "HV_SYS_REG_DBGWCR2_EL1";
        case HV_SYS_REG_DBGBVR3_EL1: return "HV_SYS_REG_DBGBVR3_EL1";
        case HV_SYS_REG_DBGBCR3_EL1: return "HV_SYS_REG_DBGBCR3_EL1";
        case HV_SYS_REG_DBGWVR3_EL1: return "HV_SYS_REG_DBGWVR3_EL1";
        case HV_SYS_REG_DBGWCR3_EL1: return "HV_SYS_REG_DBGWCR3_EL1";
        case HV_SYS_REG_DBGBVR4_EL1: return "HV_SYS_REG_DBGBVR4_EL1";
        case HV_SYS_REG_DBGBCR4_EL1: return "HV_SYS_REG_DBGBCR4_EL1";
        case HV_SYS_REG_DBGWVR4_EL1: return "HV_SYS_REG_DBGWVR4_EL1";
        case HV_SYS_REG_DBGWCR4_EL1: return "HV_SYS_REG_DBGWCR4_EL1";
        case HV_SYS_REG_DBGBVR5_EL1: return "HV_SYS_REG_DBGBVR5_EL1";
        case HV_SYS_REG_DBGBCR5_EL1: return "HV_SYS_REG_DBGBCR5_EL1";
        case HV_SYS_REG_DBGWVR5_EL1: return "HV_SYS_REG_DBGWVR5_EL1";
        case HV_SYS_REG_DBGWCR5_EL1: return "HV_SYS_REG_DBGWCR5_EL1";
        case HV_SYS_REG_DBGBVR6_EL1: return "HV_SYS_REG_DBGBVR6_EL1";
        case HV_SYS_REG_DBGBCR6_EL1: return "HV_SYS_REG_DBGBCR6_EL1";
        case HV_SYS_REG_DBGWVR6_EL1: return "HV_SYS_REG_DBGWVR6_EL1";
        case HV_SYS_REG_DBGWCR6_EL1: return "HV_SYS_REG_DBGWCR6_EL1";
        case HV_SYS_REG_DBGBVR7_EL1: return "HV_SYS_REG_DBGBVR7_EL1";
        case HV_SYS_REG_DBGBCR7_EL1: return "HV_SYS_REG_DBGBCR7_EL1";
        case HV_SYS_REG_DBGWVR7_EL1: return "HV_SYS_REG_DBGWVR7_EL1";
        case HV_SYS_REG_DBGWCR7_EL1: return "HV_SYS_REG_DBGWCR7_EL1";
        case HV_SYS_REG_DBGBVR8_EL1: return "HV_SYS_REG_DBGBVR8_EL1";
        case HV_SYS_REG_DBGBCR8_EL1: return "HV_SYS_REG_DBGBCR8_EL1";
        case HV_SYS_REG_DBGWVR8_EL1: return "HV_SYS_REG_DBGWVR8_EL1";
        case HV_SYS_REG_DBGWCR8_EL1: return "HV_SYS_REG_DBGWCR8_EL1";
        case HV_SYS_REG_DBGBVR9_EL1: return "HV_SYS_REG_DBGBVR9_EL1";
        case HV_SYS_REG_DBGBCR9_EL1: return "HV_SYS_REG_DBGBCR9_EL1";
        case HV_SYS_REG_DBGWVR9_EL1: return "HV_SYS_REG_DBGWVR9_EL1";
        case HV_SYS_REG_DBGWCR9_EL1: return "HV_SYS_REG_DBGWCR9_EL1";
        case HV_SYS_REG_DBGBVR10_EL1: return "HV_SYS_REG_DBGBVR10_EL1";
        case HV_SYS_REG_DBGBCR10_EL1: return "HV_SYS_REG_DBGBCR10_EL1";
        case HV_SYS_REG_DBGWVR10_EL1: return "HV_SYS_REG_DBGWVR10_EL1";
        case HV_SYS_REG_DBGWCR10_EL1: return "HV_SYS_REG_DBGWCR10_EL1";
        case HV_SYS_REG_DBGBVR11_EL1: return "HV_SYS_REG_DBGBVR11_EL1";
        case HV_SYS_REG_DBGBCR11_EL1: return "HV_SYS_REG_DBGBCR11_EL1";
        case HV_SYS_REG_DBGWVR11_EL1: return "HV_SYS_REG_DBGWVR11_EL1";
        case HV_SYS_REG_DBGWCR11_EL1: return "HV_SYS_REG_DBGWCR11_EL1";
        case HV_SYS_REG_DBGBVR12_EL1: return "HV_SYS_REG_DBGBVR12_EL1";
        case HV_SYS_REG_DBGBCR12_EL1: return "HV_SYS_REG_DBGBCR12_EL1";
        case HV_SYS_REG_DBGWVR12_EL1: return "HV_SYS_REG_DBGWVR12_EL1";
        case HV_SYS_REG_DBGWCR12_EL1: return "HV_SYS_REG_DBGWCR12_EL1";
        case HV_SYS_REG_DBGBVR13_EL1: return "HV_SYS_REG_DBGBVR13_EL1";
        case HV_SYS_REG_DBGBCR13_EL1: return "HV_SYS_REG_DBGBCR13_EL1";
        case HV_SYS_REG_DBGWVR13_EL1: return "HV_SYS_REG_DBGWVR13_EL1";
        case HV_SYS_REG_DBGWCR13_EL1: return "HV_SYS_REG_DBGWCR13_EL1";
        case HV_SYS_REG_DBGBVR14_EL1: return "HV_SYS_REG_DBGBVR14_EL1";
        case HV_SYS_REG_DBGBCR14_EL1: return "HV_SYS_REG_DBGBCR14_EL1";
        case HV_SYS_REG_DBGWVR14_EL1: return "HV_SYS_REG_DBGWVR14_EL1";
        case HV_SYS_REG_DBGWCR14_EL1: return "HV_SYS_REG_DBGWCR14_EL1";
        case HV_SYS_REG_DBGBVR15_EL1: return "HV_SYS_REG_DBGBVR15_EL1";
        case HV_SYS_REG_DBGBCR15_EL1: return "HV_SYS_REG_DBGBCR15_EL1";
        case HV_SYS_REG_DBGWVR15_EL1: return "HV_SYS_REG_DBGWVR15_EL1";
        case HV_SYS_REG_DBGWCR15_EL1: return "HV_SYS_REG_DBGWCR15_EL1";
        case HV_SYS_REG_MIDR_EL1: return "HV_SYS_REG_MIDR_EL1";
        case HV_SYS_REG_MPIDR_EL1: return "HV_SYS_REG_MPIDR_EL1";
        case HV_SYS_REG_ID_AA64PFR0_EL1: return "HV_SYS_REG_ID_AA64PFR0_EL1";
        case HV_SYS_REG_ID_AA64PFR1_EL1: return "HV_SYS_REG_ID_AA64PFR1_EL1";
        case HV_SYS_REG_ID_AA64DFR0_EL1: return "HV_SYS_REG_ID_AA64DFR0_EL1";
        case HV_SYS_REG_ID_AA64DFR1_EL1: return "HV_SYS_REG_ID_AA64DFR1_EL1";
        case HV_SYS_REG_ID_AA64ISAR0_EL1: return "HV_SYS_REG_ID_AA64ISAR0_EL1";
        case HV_SYS_REG_ID_AA64ISAR1_EL1: return "HV_SYS_REG_ID_AA64ISAR1_EL1";
        case HV_SYS_REG_ID_AA64MMFR0_EL1: return "HV_SYS_REG_ID_AA64MMFR0_EL1";
        case HV_SYS_REG_ID_AA64MMFR1_EL1: return "HV_SYS_REG_ID_AA64MMFR1_EL1";
        case HV_SYS_REG_ID_AA64MMFR2_EL1: return "HV_SYS_REG_ID_AA64MMFR2_EL1";
        case HV_SYS_REG_SCTLR_EL1: return "HV_SYS_REG_SCTLR_EL1";
        case HV_SYS_REG_CPACR_EL1: return "HV_SYS_REG_CPACR_EL1";
        case HV_SYS_REG_TTBR0_EL1: return "HV_SYS_REG_TTBR0_EL1";
        case HV_SYS_REG_TTBR1_EL1: return "HV_SYS_REG_TTBR1_EL1";
        case HV_SYS_REG_TCR_EL1: return "HV_SYS_REG_TCR_EL1";
        case HV_SYS_REG_APIAKEYLO_EL1: return "HV_SYS_REG_APIAKEYLO_EL1";
        case HV_SYS_REG_APIAKEYHI_EL1: return "HV_SYS_REG_APIAKEYHI_EL1";
        case HV_SYS_REG_APIBKEYLO_EL1: return "HV_SYS_REG_APIBKEYLO_EL1";
        case HV_SYS_REG_APIBKEYHI_EL1: return "HV_SYS_REG_APIBKEYHI_EL1";
        case HV_SYS_REG_APDAKEYLO_EL1: return "HV_SYS_REG_APDAKEYLO_EL1";
        case HV_SYS_REG_APDAKEYHI_EL1: return "HV_SYS_REG_APDAKEYHI_EL1";
        case HV_SYS_REG_APDBKEYLO_EL1: return "HV_SYS_REG_APDBKEYLO_EL1";
        case HV_SYS_REG_APDBKEYHI_EL1: return "HV_SYS_REG_APDBKEYHI_EL1";
        case HV_SYS_REG_APGAKEYLO_EL1: return "HV_SYS_REG_APGAKEYLO_EL1";
        case HV_SYS_REG_APGAKEYHI_EL1: return "HV_SYS_REG_APGAKEYHI_EL1";
        case HV_SYS_REG_SPSR_EL1: return "HV_SYS_REG_SPSR_EL1";
        case HV_SYS_REG_ELR_EL1: return "HV_SYS_REG_ELR_EL1";
        case HV_SYS_REG_SP_EL0: return "HV_SYS_REG_SP_EL0";
        case HV_SYS_REG_AFSR0_EL1: return "HV_SYS_REG_AFSR0_EL1";
        case HV_SYS_REG_AFSR1_EL1: return "HV_SYS_REG_AFSR1_EL1";
        case HV_SYS_REG_ESR_EL1: return "HV_SYS_REG_ESR_EL1";
        case HV_SYS_REG_FAR_EL1: return "HV_SYS_REG_FAR_EL1";
        case HV_SYS_REG_PAR_EL1: return "HV_SYS_REG_PAR_EL1";
        case HV_SYS_REG_MAIR_EL1: return "HV_SYS_REG_MAIR_EL1";
        case HV_SYS_REG_AMAIR_EL1: return "HV_SYS_REG_AMAIR_EL1";
        case HV_SYS_REG_VBAR_EL1: return "HV_SYS_REG_VBAR_EL1";
        case HV_SYS_REG_CONTEXTIDR_EL1: return "HV_SYS_REG_CONTEXTIDR_EL1";
        case HV_SYS_REG_TPIDR_EL1: return "HV_SYS_REG_TPIDR_EL1";
        case HV_SYS_REG_CNTKCTL_EL1: return "HV_SYS_REG_CNTKCTL_EL1";
        case HV_SYS_REG_CSSELR_EL1: return "HV_SYS_REG_CSSELR_EL1";
        case HV_SYS_REG_TPIDR_EL0: return "HV_SYS_REG_TPIDR_EL0";
        case HV_SYS_REG_TPIDRRO_EL0: return "HV_SYS_REG_TPIDRRO_EL0";
        case HV_SYS_REG_CNTV_CTL_EL0: return "HV_SYS_REG_CNTV_CTL_EL0";
        case HV_SYS_REG_CNTV_CVAL_EL0: return "HV_SYS_REG_CNTV_CVAL_EL0";
        case HV_SYS_REG_SP_EL1: return "HV_SYS_REG_SP_EL1";
        default: return "?";
    }
}
} // namespace ohv
