
import re
SRC="/Users/libr/Desktop/life/vphone-qemu/.scratch/hvf-ida/OpenHypervisor/include/openhyp/hv_compat_enums.h"
DST="/Users/libr/Desktop/life/vphone-qemu/.scratch/hvf-ida/OpenHypervisor/src/ohv_sysreg_table.cpp"
txt=open(SRC).read()
entries=re.findall(r"(HV_SYS_REG_[A-Za-z0-9_]+)\s*(?:=\s*(0x[0-9a-fA-F]+|\d+))?",txt)
seen={}; order=[]
for name,val in entries:
    if name in seen: continue
    seen[name]=val; order.append(name)
banked=["TTBR0_EL1","TTBR1_EL1","TCR_EL1","ELR_EL1","FAR_EL1","ESR_EL1","MAIR_EL1","AMAIR_EL1",
"VBAR_EL1","CNTV_CVAL_EL0","CNTP_CVAL_EL0","ACTLR_EL1","SCTLR_EL1","CPACR_EL1","SPSR_EL1",
"AFSR0_EL1","AFSR1_EL1","CONTEXTIDR_EL1","CNTV_CTL_EL0","CNTP_CTL_EL0","CNTKCTL_EL1",
"ICH_VMCR_EL2","SCXTNUM_EL1","SMCR_EL1"]
shared=["MDSCR_EL1","TPIDR_EL1","TPIDR_EL0","TPIDRRO_EL0","SP_EL0","SP_EL1","PAR_EL1","CSSELR_EL1",
"AFPCTL","AFPCR_EL0","SCXTNUM_EL0","TPIDR2_EL0","SMPRI_EL1"]
def classify(name):
    short=name[len("HV_SYS_REG_"):]
    if short.startswith("DBG"):
        for pre,arr in (("DBGBVR","bvr"),("DBGBCR","bcr"),("DBGWVR","wvr"),("DBGWCR","wcr")):
            if short.startswith(pre):
                try: return ("dbg_"+arr,int(short[len(pre):].split("_")[0]))
                except ValueError: pass
    if short=="MDCCINT_EL1": return ("dbg_mdccint",None)
    if short=="MDSCR_EL1": return ("shared",shared.index("MDSCR_EL1"))
    if short in shared: return ("shared",shared.index(short))
    if short in banked: return ("banked",banked.index(short))
    if short.startswith("ID_") or short in ("MIDR_EL1","MPIDR_EL1","CTR_EL0","CLIDR_EL1","DCZID_EL0"):
        return ("roid",None)
    ptrauth={"APGAKEYHI":30,"APGAKEYLO":31,"APIAKEYHI":32,"APIAKEYLO":33,"APIBKEYHI":34,"APIBKEYLO":35,"APDAKEYHI":36,"APDAKEYLO":37,"APDBKEYHI":38,"APDBKEYLO":39}
    if short.removesuffix("_EL1") in ptrauth:
        return ("extreg",ptrauth[short.removesuffix("_EL1")])
    return ("unknown",None)
out=["// GENERATED by tools/gen_sysreg_table.py - do not edit by hand.",
     "#include \"ohv_internal.h\"",
     "namespace ohv {"]
tbl=["static const SysRegDesc kTable[] = {"]
body=[]
n=0
miss=[]
for name in order:
    val=seen[name]; kind,idx=classify(name); enc=val
    if enc is None or kind=="unknown":
        miss.append(name); continue
    if kind=="bvr":   entry="{%s,3,%d*2,OHV_STATE_DEBUG,false}"%(enc,idx); body.append("    case %s: return &kTable[%d];"%(name,n))
    elif kind=="bcr": entry="{%s,3,%d*2+1,OHV_STATE_DEBUG,false}"%(enc,idx); body.append("    case %s: return &kTable[%d];"%(name,n))
    elif kind=="wvr": entry="{%s,3,32+%d*2,OHV_STATE_DEBUG,false}"%(enc,idx); body.append("    case %s: return &kTable[%d];"%(name,n))
    elif kind=="wcr": entry="{%s,3,32+%d*2+1,OHV_STATE_DEBUG,false}"%(enc,idx); body.append("    case %s: return &kTable[%d];"%(name,n))
    elif kind=="dbg_mdccint": entry="{%s,3,64,OHV_STATE_DEBUG,true}"%enc; body.append("    case %s: return &kTable[%d];"%(name,n))
    elif kind=="shared": entry="{%s,0,%d,0,false}"%(enc,idx); body.append("    case %s: return &kTable[%d];"%(name,n))
    elif kind=="banked": entry="{%s,1,%d,OHV_STATE_SYSREGS,true}"%(enc,idx); body.append("    case %s: return &kTable[%d];"%(name,n))
    elif kind=="extreg": entry="{%s,2,%d,OHV_STATE_PTRAUTH_ARM,true}"%(enc,idx); body.append("    case %s: return &kTable[%d];"%(name,n))
    else: entry="{%s,5,0,0,false}"%enc; body.append("    case %s: return &kTable[%d];"%(name,n))
    tbl.append("    %s,"%entry); n+=1
tbl.append("};")
tail=["    default: return nullptr;",
      "    }",
      "}",
      "const char *sysreg_name(uint16_t enc) {",
      "    switch (enc) {"]
for name in order:
    if seen[name]: tail.append('        case %s: return "%s";'%(name,name))
tail+=['        default: return "?";',
       "    }",
       "}",
       "} // namespace ohv"]
out=out+tbl+["const SysRegDesc *sysreg_lookup(uint16_t enc) {","    switch (enc) {"]+body+tail

open(DST,"w").write("\n".join(out)+"\n")
print("mapped:",n,"unmapped:",len(miss))
print("unmapped:",miss[:15])